export const SET_VIDEO = 'SET_VIDEO';
export const SET_VIDEO_DURATION = 'SET_VIDEO_DURATION';
export const SET_GIF = 'SET_GIF';
export const SET_GIF_START = 'SET_GIF_START';
export const SET_GIF_END = 'SET_GIF_END';
export const SET_PERCENTAGE_COMPLETION = 'SET_PERCENTAGE_COMPLETION';
export const SET_LOADING = 'SET_LOADING';
