export const SET_VIDEO = 'SET_VIDEO';
export const SET_VIDEO_DURATION = 'SET_VIDEO_DURATION';
export const SET_MEDIA_PRESENT = 'SET_MEDIA_PRESENT';
export const SET_PERCENTAGE_COMPLETION = 'SET_PERCENTAGE_COMPLETION';
export const SET_LOADING = 'SET_LOADING';
